name: maven_build
on: [push, workflow_dispatch]
jobs: 
  build:
     name: Build and Install
     runs-on: ubuntu-latest 
     steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Install Dependencies
      #   run: mvn install
      # - name: Build with Maven
        run: mvn -f pom.xml clean package -DskipTests=true
      - name: List files in workspace
        run: ls -R
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.4
        with: 
          name: drop
          path: ./target/myshuttledev.war

