name: maven_build
on: [push, workflow_dispatch]
jobs: 
  build:
     name: Build and Install
     runs-on: ubuntu-latest 
     steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Install Dependencies
      #   run: mvn install
      # - name: Build with Maven
        run: mvn -f pom.xml clean package -DskipTests=true
      - name: List files in workspace
        run: ls -R
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.4
        with: 
          name: drop
          path: ./target/myshuttledev.war
  deploy:
    name: Deploy Stage
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: sudo mkdir /home/artifact
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: drop
          path: /home/artifact/
      - run: ls -R
      # - run: cd /home/runner/artifact
      - run: cd /home/runner/work/MyShuttle/MyShuttle/
      - run: pwd
      - run: ls -R
      - run: |
            git init
          # git config --global init.defaultBranch main
          # git config --global user.email "mihir11kulkarni@gmail.com"
          # git config --global user.name "Mihir11"  
          
          # git remote add origin https://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@github.com/MihirKulkarni11/Deploy.git
          # git add .
          # git commit -m "First commit"
          # git push
          # # git push -u origin main









      
      # - run: git init
      # - run: |
      #    git remote add origin https://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@github.com/MihirKulkarni11/Deploy.git \
      #    # git add . \
      #    git commit -m "first commit" \
      #    git branch -M main \
      #    git push -u origin main
      
  # # You may pin to the exact commit or the version.
  # # uses: tech-thinker/push-to-repo@a599ed57544bc8348c09cba83a5ffc790b2ead6723456
  #       uses: tech-thinker/push-to-repo@v1.0.0
  #       with:
  #   # Source directory from the origin directory
  #        source-directory: ./target/**
  #   # Name of the destination username/organization
  #        destination-github-username: MihirKulkarni11
  #   # Destination repository
  #        destination-repository-name: https://github.com/MihirKulkarni11/Deploy.git
  #        entryPoint: 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

          
      
 







