name: maven_build
on: push
  workflow_dispatch: 
jobs: 
  install:
     name: maveninstall
     runs-on: ubuntu-latest 
     steps:
      - uses: actions/checkout@v1
      - name: install Dependencies
      - run: npm install 
  build:
     name: action-maven
      - uses: comchangs/action-maven@v0.4-beta
      - run: npm run build --if-present
      - run: npm publish
