name: maven_build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build and Install
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Install Dependencies
        run: mvn install -B -DskipTests=true

      - name: Build with Maven
        run: mvn -f pom.xml clean package -DskipTests=true

      - name: List files in workspace
        run: ls -R

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: drop
          path: ./target/myshuttledev.war

  deploy:
    name: Deploy Stage
    needs: build
    runs-on: ubuntu-latest
    # env:
      # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
    steps:
      - name: Create Directory for Artifacts
        run: sudo mkdir -p /home/artifact/drop

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: drop
          path: /home/artifact/droop

      - name: Debug Downloaded Files
        run: ls -al /home/artifact/drop

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      - name: S3 Artifact Upload
        uses: usualdesigner/s3-artifact-upload@v1.0.15
        with: 
          bucket-name: githubselfhostedrunner 
          file: /home/artifact/drop
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
        
        


      
      
      
      
      
      
      
      
      
      # - name: Deploy to S3
      #   uses: jakejarvis/s3-sync-action@v0.5.1
      #   with:
      #     AWS_S3_BUCKET: githubselfhostedrunner
      #     AWS_ACCESS_KEY_ID: ${{secrets.AWS_SECRET_ACCESS_ID}}
      #     AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_ID}}
      #     AWS_REGION: us-east-1
      #     SOURCE_DIR: /home/artifact/droop
      #     DEST_DIR: / 







      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #       aws-access-key-id: ${{ secrets.AWSACCESSKEY }}
      #       aws-secret-access-key: ${{ secrets.AWSSECRETSKEY }}
      #       aws-region: us-east-1
        
      # - name: S3 Artifact Upload
      #   uses: usualdesigner/s3-artifact-upload@v1.0.15

      # - name: Upload artifacts to AWS S3
      #   uses: usualdesigner/s3-artifact-upload@main
      #   with:
      #     bucket-name: ${{ secrets.AWSBUCKET }}
      #     file: /home/artifact/drop/myshuttledev.war
        





































            # - name: Upload to S3
      #   uses: shallwefootball/upload-s3-action@v1.3.3
      #   id: S3
      #   with:
      #     echo: ${{secrets.AWS_SECRET_ACCESS_ID}}
      #     # echo: ${{secrets.AWS_SECRET_ACCESS_KEY}} 
      #     aws_key_id: ${{secrets.AWS_SECRET_ACCESS_ID}}
      #     aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      #     aws_bucket: githubselfhostedrunner
      #     source_dir: '/home/artifact/drop'




      
        
      # - name: AWS S3 Uploader
      #   uses: oneyedev/aws-deploy-s3@v2
      #   env:
      #    AWS_ACCESS_KEY_ID: ${{ secrets.AWSACCESSKEY }}
      #    SECRET_ACCESS_KEY: ${{ secrets.AWSSECRETSKEY }}
         
      #   with:
      #    region: us-east-1
      #    bucket: githubselfhostedrunner
      #    source: /home/artifact/drop
      #    target: githubselfhostedrunner/thefolder

      # - name: AWS Deploy S3
      #   uses: oneyedev/aws-deploy-s3@v2
      #   with:
      #     region: us-east-1
      #     bucket: githubselfhostedrunner 
      #     source: /home/artifact/drop
      #     target: githubselfhostedrunner/thefolder
      #     aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWSSECRETSKEY }}
      # -  env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        

      
      
      
      
      
      
      
      
      # - name: Upload to S3
      #   uses: edgeetech/s3-upload-action@1.3.3
      #   with:
      #     aws_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
      #     aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
      #     aws_bucket: githubselfhostedrunner 
      #     source_dir: /home/artifact/drop
      #     destination_dir: githubselfhostedrunner/thefolder/
      
      # - name: AWS S3 Uploader
      #   uses: edgeetech/s3-upload-action@1.3.3
      #   with:
      #     aws_key_id: ${{ secrets.AWSACCESSKEY }}
      #     aws_secret_access_key: ${{ secrets.AWSSECRETSKEY }}
      #     aws_bucket: githubselfhostedrunner
      #     source_dir: /home/artifact/drop
      #     destination_dir: /






























# name: maven_build

# on:
#   push:
#     branches:
#       - master
#   workflow_dispatch:

# jobs:
#   build:
#     name: Build and Install
#     runs-on: self-hosted
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up JDK 1.8
#         uses: actions/setup-java@v2
#         with:
#           java-version: '8'
#           distribution: 'adopt'

#       - name: Install Dependencies
#         run: mvn install -B -DskipTests=true

#       - name: Build with Maven
#         run: mvn -f pom.xml clean package -DskipTests=true

#       - name: List files in workspace
#         run: ls -R

#       - name: Upload a Build Artifact
#         uses: actions/upload-artifact@v4.3.4
#         with:
#           name: drop
#           path: ./target/myshuttledev.war

#   deploy:
#     name: Deploy Stage
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Create Directory for Artifacts
#         run: sudo mkdir -p /home/artifact/drop
        
#       - name: List files in /home/artifact/
#         run: ls -al /home/artifact/drop

#       - name: Download a Build Artifact
#         uses: actions/download-artifact@v4.1.8
#         with:
#           name: drop
#           path: /home/artifact/
          
#       - name: Debug Paths
#         run: ls -al /home/artifact/drop
        
#       - name: AWS S3 Uploader
#         uses: edgeetech/s3-upload-action@1.3.3
#         with:
#           aws_key_id: ${{ secrets.AWSACCESSKEY }}
#           aws_secret_access_key: ${{ secrets.AWSSECRETSKEY }}
#           aws_bucket: githubselfhostedrunner
#           source_dir: /home/artifact/drop
#           destination_dir: s3://githubselfhostedrunner/thefolder/
          
 
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      # - name: Upload to S3
      #   uses: jakejarvis/s3-sync-action@0.5.0
      #   with:
      #     args: --delete --exact-timestamps /home/artifact/ s3://githubselfhostedrunner/
      #   env:
      #       aws_key_id: ${{ secrets.AWSACCESSKEY }}
      #       aws_secret_access_key: ${{ secrets.AWSSECRETSKEY }}
      #       AWSBucket: ${{ secrets.AWSBucket }}
      
      
      
      
      
      
      
      
      
      
      
      # - name: AWS S3 Uploader
      #   uses: edgeetech/s3-upload-action@1.3.3
      #   with:
      #     aws_key_id: ${{ secrets.AWSACCESSKEY }}
      #     aws_secret_access_key: ${{ secrets.AWSSECRETSKEY }}
      #     aws_bucket: githubselfhostedrunner
      #     source_dir: /home/artifact/


          

  #     - name: Set up Git
  #       run: |
  #         git config --global user.email "your-email@example.com"
  #         git config --global user.name "Your Name"

  #     - run: cd /home/artifact

  #     - name: Initialize Git repository
  #       run: git init
  #     - name: Check Git status
  #       run: git status

  #     - name: Add remote repository
  #       run: git remote add origin https://github.com/your-username/your-repo.git

  #     - name: Configure Git user
  #       run: |
  #         git config --global user.email "your-email@example.com"
  #         git config --global user.name "Your Name"

  #     - name: Checkout main branch
  #       run: git checkout -b main

  #     - name: Copy artifact to repository
  #       run: cp /home/artifact/myshuttledev.war ./myshuttledev.war

  #     - name: Add artifact to Git
  #       run: git add myshuttledev.war

  #     - name: Commit changes
  #       run: git commit -m "Add myshuttledev.war artifact"

  #     - name: Push to GitHub repository
  #       run: git push origin main
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  # deploy:
  #   name: Deploy Stage
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: sudo mkdir /home/artifact
  #     - name: Download a Build Artifact
  #       uses: actions/download-artifact@v4.1.8
  #       with:
  #         name: drop
  #         path: /home/artifact/
  #     - run: ls -R
  #     # - run: cd /home/runner/artifact
  #     - run: cd /home/runner/work/MyShuttle/MyShuttle/
  #     - run: pwd
  #     - run: ls -R
  #     - run: |
  #           git init
          # git config --global init.defaultBranch main
          # git config --global user.email "mihir11kulkarni@gmail.com"
          # git config --global user.name "Mihir11"  
          
          # git remote add origin https://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@github.com/MihirKulkarni11/Deploy.git
          # git add .
          # git commit -m "First commit"
          # git push
          # # git push -u origin main









      
      # - run: git init
      # - run: |
      #    git remote add origin https://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@github.com/MihirKulkarni11/Deploy.git \
      #    # git add . \
      #    git commit -m "first commit" \
      #    git branch -M main \
      #    git push -u origin main
      
  # # You may pin to the exact commit or the version.
  # # uses: tech-thinker/push-to-repo@a599ed57544bc8348c09cba83a5ffc790b2ead6723456
  #       uses: tech-thinker/push-to-repo@v1.0.0
  #       with:
  #   # Source directory from the origin directory
  #        source-directory: ./target/**
  #   # Name of the destination username/organization
  #        destination-github-username: MihirKulkarni11
  #   # Destination repository
  #        destination-repository-name: https://github.com/MihirKulkarni11/Deploy.git
  #        entryPoint: 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

          
      
 







