name: maven_build
on: [push, workflow_dispatch]
jobs: 
  install:
     name: maveninstall
     runs-on: ubuntu-latest 
     steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: install Dependencies
        run: mvn install
  build:
     name: action-maven
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -f ./pom.xml clean package -DSkipTest
